#!/bin/zsh

source $HOME/.zshenv

selected=$(printf "zsh\nbspwm\nsxhkd\npolybar\nkitty\nnvim\npicom\nranger\naliases\nhistory\nconfs" | fzf --layout=reverse --border)

case $selected in
    zsh)
        bspc node focused.floating -t tiled
        vi $XDG_CONFIG_HOME/zsh/.zshrc
        ;;
    bspwm)
        bspc node focused.floating -t tiled
        vi $XDG_CONFIG_HOME/bspwm/bspwmrc
    ;;
    sxhkd)
        bspc node focused.floating -t tiled
        vi $XDG_CONFIG_HOME/sxhkd/sxhkdrc
    ;;
    polybar)
        bspc node focused.floating -t tiled
        vi $XDG_CONFIG_HOME/polybar/config
    ;;
    kitty)
        bspc node focused.floating -t tiled
        vi $XDG_CONFIG_HOME/kitty/kitty.conf
    ;;
    nvim)
        bspc node focused.floating -t tiled
        vi $XDG_CONFIG_HOME/nvim/
    ;;
    picom)
        bspc node focused.floating -t tiled
        vi $XDG_CONFIG_HOME/picom/picom.conf
    ;;
    ranger)
        bspc node focused.floating -t tiled
        vi $XDG_CONFIG_HOME/ranger/rc.conf
    ;;
    aliases)
        bspc node focused.floating -t tiled
        vi $XDG_CONFIG_HOME/zsh/.aliases
    ;;
    history)
        bspc node focused.floating -t tiled
        vi $XDG_CONFIG_HOME/zsh/.history
    ;;
    confs)
        bspc node focused.floating -t tiled
        vi $HOME/.local/scripts/confs
    ;;
esac
