#!/bin/zsh

export FZF_DEFAULT_OPTS=$OPTS_ALL$FZF_DEF$OPTS_MENU' --prompt="漣 " --header="CONFIGURATIONS"'
selected=$(printf "zsh\nbspwm\nsxhkd\npolybar\nkitty\nnvim\npicom\nranger\naliases\nhistory\ntmux\nkmonad\nconfigs" | fzf --layout=reverse)

case $selected in
    zsh)
        bspc node focused.floating -t tiled
        sleep 0.2
        vi $XDG_CONFIG_HOME/zsh/.zshrc
        ;;
    bspwm)
        bspc node focused.floating -t tiled
        sleep 0.2
        vi $XDG_CONFIG_HOME/bspwm/bspwmrc
    ;;
    sxhkd)
        bspc node focused.floating -t tiled
        sleep 0.2
        vi $XDG_CONFIG_HOME/sxhkd/sxhkdrc
    ;;
    polybar)
        bspc node focused.floating -t tiled
        sleep 0.2
        vi $XDG_CONFIG_HOME/polybar/config
    ;;
    kitty)
        bspc node focused.floating -t tiled
        sleep 0.2
        vi $XDG_CONFIG_HOME/kitty/kitty.conf
    ;;
    nvim)
        bspc node focused.floating -t tiled
        sleep 0.2
        vi $XDG_CONFIG_HOME/nvim/
    ;;
    picom)
        bspc node focused.floating -t tiled
        sleep 0.2
        vi $XDG_CONFIG_HOME/picom/picom.conf
    ;;
    ranger)
        bspc node focused.floating -t tiled
        sleep 0.2
        vi $XDG_CONFIG_HOME/ranger/rc.conf
    ;;
    aliases)
        bspc node focused.floating -t tiled
        sleep 0.2
        vi $XDG_CONFIG_HOME/zsh/.aliases
    ;;
    history)
        bspc node focused.floating -t tiled
        sleep 0.2
        vi $XDG_CONFIG_HOME/zsh/.history
    ;;
    tmux)
        bspc node focused.floating -t tiled
        sleep 0.2
        vi $HOME/.tmux.conf
    ;;
    kmonad)
        bspc node focused.floating -t tiled
        sleep 0.2
        vi $XDG_CONFIG_HOME/kmonad/config.kbd
    ;;

    configs)
        bspc node focused.floating -t tiled
        sleep 0.2
        vi $HOME/.local/scripts/fzfconfigs
    ;;
esac
