#!/bin/zsh

source $HOME/.zshenv

selected=$(printf " cancel\n襤shutdown\n reboot\n logout"|fzf --layout=reverse --border)

case $selected in
    " cancel")
        ;;
    "襤shutdown")
        selected=$(printf " no\n yes"|fzf --layout=reverse --border)
        if [[ "$selected" == " yes" ]]
        then
            exec systemctl poweroff
        fi
        ;;
    " reboot")
        selected=$(printf " no\n yes"|fzf --layout=reverse --border)
        if [[ "$selected" == " yes" ]]
        then
            exec systemctl reboot
        fi
        ;;
    " logout")
        selected=$(printf " no\n yes"|fzf --layout=reverse --border)
        if [[ "$selected" == " yes" ]]
        then
            loginctl terminate-session ${XDG_SESSION_ID-} 
        fi
        ;;
esac
