#!/bin/zsh

export FZF_DEFAULT_OPTS=$OPTS_ALL$FZF_DEF$OPTS_MENU' --prompt=" " --header="URLS"'

urls=$(cat $HOME/bookmarks)

selected=$(printf $urls | fzf --layout=reverse)
if [ -z $selected ]; then
    exit 0
fi
WID="$(xdo id)"
xdo hide
firefox --new-instance -P default --class=firefox-fzf --new-window $selected
xdo show "$WID"
